class TerminationConstants {
  static const List<String> columns = [
    'Badge_NO',
    'Employee_Name',
    'Grade',
    'Termination_Date',
    'Old_Basic',
    'Adjust_Months',
    'Adjustment',
    'Old_Basic_Plus_Adj',
    'Adjust_Date',
    'Appraisal_Text',
    'Annual_Increment',
    'Appraisal_NO_of_Months',
    'Appraisal_Amount',
    'Appraisal_Date',
    'New_Basic',
    'Current_Lump_Sum',
    'Amount_Div_12',
    'Amount_Div_12_Per_Month',
    'No_of_Months',
    'No_of_Days',
    'New_Lump_Sum',
    'Transfer_Action',
  ];

  static const Map<String, String> columnNames = {
    'Badge_NO': 'B.No',
    'Employee_Name': 'Name',
    'Grade': 'Grade',
    'Termination_Date': 'Term/Date',
    'Old_Basic': 'Old Basic',
    'Adjust_Months': 'Adjust NO of Months',
    'Adjustment': 'Adjustment',
    'Old_Basic_Plus_Adj': 'Old Basic + Adj',
    'Adjust_Date': 'Adjust.Date',
    'Appraisal_Text': 'Appraisal Text',
    'Annual_Increment': 'Annual Increment',
    'Appraisal_NO_of_Months': 'Appraisal NO of Months',
    'Appraisal_Amount': 'Appraisal Amount',
    'Appraisal_Date': 'Appraisal Date',
    'New_Basic': 'New Basic',
    'Current_Lump_Sum': 'Current Lump sum',
    'Amount_Div_12': 'Amount/12',
    'Amount_Div_12_Per_Month': '(Amount/12)/Month',
    'No_of_Months': 'No of Months',
    'No_of_Days': 'No of Days',
    'New_Lump_Sum': 'New Lump Sum',
    'Transfer_Action': 'Terminate',
  };

  static const int pageSize = 50;
}
